Projekt/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt.Models.Addresses;
using Projekt.Models.Producer;

namespace Projekt.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProducerController : Controller
    {
        private readonly IProducerService _producerService;
        private readonly IAddressService _addressService;

        public ProducerController(IProducerService producerService, IAddressService addressService)
        {
            _producerService = producerService;
            _addressService = addressService;
        }

        // MAIN VIEW
        // GET: /Producer
        [AllowAnonymous]
        public IActionResult Index()
        {
            var producerList = _producerService.GetAllProducers();
            return View(producerList);
        }

        // DETAILS
        // GET: /Producer/Details/1
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var producer = _producerService.GetProducerById(id);
            var address = _addressService.GetAddressById(producer.AddressId);
            ViewBag.Address = address;

            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        // ADDING
        // GET: /Producer/Create
        [HttpGet]
        public IActionResult Create()
        {
            var addresses = _addressService.GetAllAddresses();
            ViewBag.Addresses = addresses;
            return View("Create");
        }

        // POST: /Producer/Create
        [HttpPost]
        public IActionResult Create(ProducerModel model)
        {
            if (ModelState.IsValid)
            {
                _producerService.AddProducer(model);
                return RedirectToAction("Index");
            }
            else
            {
                var addresses = _addressService.GetAllAddresses();
                ViewBag.Addresses = addresses;
                return View("Create", model);
            }
        }

        // EDITING
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var addresses = _addressService.GetAllAddresses();
            var producer = _producerService.GetProducerById(id);

            ViewBag.Addresses = addresses;

            if (producer == null)
            {
                return NotFound();
            }

            return View("Edit", producer);
        }

        [HttpPost]
        public IActionResult Edit(ProducerModel model)
        {
            if (ModelState.IsValid)
            {
                _producerService.UpdateProducer(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Edit", model);
            }
        }

        // DELETING
        // GET: /Producer/Delete/1
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = _producerService.GetProducerById(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: /Producer/DeleteConfirmed/1
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var product = _producerService.GetProducerById(id);

            if (product == null)
            {
                return NotFound();
            }

            _producerService.DeleteProducer(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddressDetails (int id)
        {
            var address = _addressService.GetAddressById(id);

            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }
        public IActionResult CreateApi()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateApi(ProducerModel model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home"); 
            }

            return View(model);
        }
    }
}

Projekt/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt.Models.Producer;
using Projekt.Models.Products;

namespace Projekt.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProducerService _producerService;

        public ProductController(IProductService productService, IProducerService producerService)
        {
            _productService = productService;
            _producerService = producerService;
        }

        // MAIN VIEW
        // GET: /Product
        [AllowAnonymous]
        public IActionResult Index()
        {
            var productList = _productService.GetAllProducts();
            return View(productList);
        }

        // DETAILS
        // GET: /Product/Details/1
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var product = _productService.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            var producerName = _producerService.GetProducerNameById(product.ProducerId);
            ViewBag.ProducerName = producerName;

            return View(product);
        }

        // ADDING
        // GET: /Product/Create
        [HttpGet]
        public IActionResult Create()
        {
            var producers = _producerService.GetAllProducers();
            ViewBag.Producers = producers;
            return View("Create");
        }

        // POST: /Product/Create
        [HttpPost]
        public IActionResult Create(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                _productService.AddProduct(model);
                return RedirectToAction("Index");
            }
            else
            {
                var producers = _producerService.GetAllProducers();
                ViewBag.Producers = producers;
                return View("Create", model);
            }
        }

        // EDITING
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var product = _productService.GetProductById(id);
            var producers = _producerService.GetAllProducers();
            ViewBag.Producers = producers;

            if (product == null)
            {
                return NotFound();
            }

            return View("Edit", product);

        }

        [HttpPost]
        public IActionResult Edit(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                var producerName = _producerService.GetProducerNameById(model.ProducerId);
                ViewBag.ProducerName = producerName;

                _productService.UpdateProduct(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Edit", model);
            }
        }

        // DELETING
        // GET: /Product/Delete/1
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = _productService.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: /Product/DeleteConfirmed/1
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var product = _productService.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }

            _productService.DeleteProduct(id);

            return RedirectToAction("Index");
        }
    }
}

Projekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Projekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projekt.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projekt</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produkty</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Producer" asp-action="Index">Producenci</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Producer" asp-action="CreateApi">API</a>
                    </li>
                     <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>
</header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Przemysław Światłoń - Projekt
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>